spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/gofit
spring.datasource.username=postgres
spring.datasource.password=$iPhone54321

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gofit.jwt.secret=change-this-before-production
gofit.jwt.expiration-seconds=86400